@startuml UC-05

skinparam actorStyle awesome
skinparam backgroundColor #fdf5f8
skinparam usecase {
    BackgroundColor #fce4ec
    BorderColor #880e4f
    FontColor #880e4f
}
skinparam actor {
    BackgroundColor #880e4f
    FontColor #880e4f
}
skinparam arrow {
    Color #880e4f
}

title UC-05 — View Invoice Detail

actor "User" as User
database "PostgreSQL" as DB
cloud "AWS S3" as S3

rectangle "IntelliInvoice System" {
    usecase "UC-05\nView Invoice Detail"     as UC05
    usecase "UC-09\nView Original Image"     as UC09
}

User  --> UC05
UC05 ..> UC09 : <<extend>>
UC05  --> DB
UC09  --> S3

@enduml